#!/bin/sh
### BEGIN INIT INFO
# Provides:          temperature-control.py
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop::    $network $local_fs $remote_fs $syslog
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Temperature-control-system
# Description:       Better then better
### END INIT INFO
#NAME = fan
export HOME="/home/pi"
export USER="root"
#PIDFILE = /home/pi/raspberry-python/temperature-control.py

python /home/pi/raspberry-python/temperature-control.py
python3 /home/pi/raspberry-python/camera.py
exit 0
